const VERSION='taskvexa-theme-v6';
self.addEventListener('install',event=>event.waitUntil(self.skipWaiting()));
self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));
self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.mode!=='navigate') return;
  event.respondWith((async()=>{
    try{
      const response=await fetch(request,{cache:'no-store'});
      const type=response.headers.get('content-type')||'';
      if(!type.includes('text/html')) return response;
      let html=await response.text();
      const bootstrap='<script>(function(){try{var t=localStorage.getItem("taskvexa-theme");if(t==="light"){document.documentElement.classList.add("tvx-light");document.documentElement.style.background="#f5f7fb"}}catch(e){}})();</script>';
      const style='<style id="taskvexa-theme-sw-style">html.tvx-light,html.tvx-light body,body.tvx-light,body.light{background:#f5f7fb!important;color:#111827!important;color-scheme:light!important}html.tvx-light header,body.tvx-light header,body.light header,html.tvx-light nav,body.tvx-light nav,body.light nav{background:#fff!important;color:#111827!important;border-color:#d9e0ea!important}html.tvx-light input,html.tvx-light textarea,html.tvx-light select,body.tvx-light input,body.tvx-light textarea,body.tvx-light select,body.light input,body.light textarea,body.light select{background:#fff!important;color:#111827!important;border-color:#cbd5e1!important}html.tvx-light .card,html.tvx-light .task,html.tvx-light .box,html.tvx-light .loading,html.tvx-light .empty,html.tvx-light .modalbox,html.tvx-light .banner,html.tvx-light .service,html.tvx-light .progress-card,html.tvx-light .activity-card,html.tvx-light .notice-card,html.tvx-light .leader,html.tvx-light .plans-sheet,html.tvx-light .activation,body.tvx-light .card,body.tvx-light .task,body.tvx-light .box,body.tvx-light .loading,body.tvx-light .empty,body.tvx-light .modalbox,body.tvx-light .banner,body.tvx-light .service,body.tvx-light .progress-card,body.tvx-light .activity-card,body.tvx-light .notice-card,body.tvx-light .leader,body.tvx-light .plans-sheet,body.tvx-light .activation,body.light .card,body.light .task,body.light .box,body.light .loading,body.light .empty,body.light .modalbox,body.light .banner,body.light .service,body.light .progress-card,body.light .activity-card,body.light .notice-card,body.light .leader,body.light .plans-sheet,body.light .activation{background:#fff!important;color:#111827!important;border-color:#d9e0ea!important}html.tvx-light .balance,body.tvx-light .balance,body.light .balance{background:linear-gradient(135deg,#4f6cf5,#8b3ff0)!important;color:#fff!important;border-color:#8060f2!important}html.tvx-light .balance *,body.tvx-light .balance *,body.light .balance *{color:#fff!important}html.tvx-light .bottom,body.tvx-light .bottom,body.light .bottom{background:#fff!important;color:#111827!important;border-color:#e2e8f0!important;box-shadow:0 -4px 18px rgba(15,23,42,.08)!important}html.tvx-light .plus,body.tvx-light .plus,body.light .plus{background:linear-gradient(135deg,#4f46e5,#7c3aed)!important;color:#fff!important}html.tvx-light .icon,body.tvx-light .icon,body.light .icon{background:#fff!important;color:#111827!important;border-color:#d9e0ea!important}html.tvx-light .banner-icon,html.tvx-light .notice-icon,html.tvx-light .avatar,body.tvx-light .banner-icon,body.tvx-light .notice-icon,body.tvx-light .avatar,body.light .banner-icon,body.light .notice-icon,body.light .avatar{background:#ede9fe!important;color:#6d28d9!important}html.tvx-light .muted,body.tvx-light .muted,body.light .muted{color:#64748b!important}html.tvx-light a,body.tvx-light a,body.light a{color:#2563eb!important}.taskvexa-theme-button,#themeToggle{z-index:2147483647!important}</style>';
      let result=html;
      if(result.includes("order('created_at',{ascending:false).limit(2)")) result=result.replaceAll("order('created_at',{ascending:false).limit(2)","order('created_at',{ascending:false}).limit(2)");
      if(!result.includes('id="taskvexa-theme-sw-style"')) result=result.includes('</head>')?result.replace('</head>',bootstrap+style+'</head>'):style+result;
      if(!result.includes('theme.js')){const script='<script src="/theme.js?v=6"></script>';result=result.includes('</body>')?result.replace('</body>',script+'</body>'):result+script}
      const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-store');
      return new Response(result,{status:response.status,statusText:response.statusText,headers});
    }catch(e){return fetch(request)}
  })());
});