(function(){
'use strict';
var KEY='taskvexa-theme',SESSION_KEY='taskvexa-login-session';
var SUPABASE_URL='https://dxtlnrthlpdaobnbazny.supabase.co';
var SUPABASE_KEY='sb_publishable_UUFlTjQiT3osVMRNFYiNuA_UukQ-9kY';
window.$=window.$||function(id){return document.getElementById(id)};
function isPromoterPage(){return /^promoter-(dashboard|campaigns|campaign-details|create|photo|my-photos|photo-campaigns|wallet|fund|submissions|settings|referrals|history)\.html$/i.test((location.pathname||'').split('/').pop()||'')}
function getClient(){try{if(window.supabaseClient&&window.supabaseClient.auth)return window.supabaseClient;if(window.supabase&&typeof window.supabase.createClient==='function'){if(!window.__tvxThemeClient)window.__tvxThemeClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return window.__tvxThemeClient}}catch(e){}return null}
function apply(){var r=document.documentElement,b=document.body;r.classList.remove('tvx-light');r.classList.add('tvx-dark');if(b){b.classList.remove('tvx-light','light');b.classList.add('tvx-dark','dark')}try{localStorage.setItem(KEY,'dark')}catch(e){}var m=document.querySelector('meta[name="theme-color"]');if(m)m.setAttribute('content','#080d18');document.querySelectorAll('#themeToggle,#taskvexa-theme-global,#theme').forEach(function(x){x.remove()})}
function ensureFilora(){var l=document.getElementById('filora-theme-css');if(!l){l=document.createElement('link');l.id='filora-theme-css';l.rel='stylesheet';l.href='/filora-theme.css?v=9';document.head.appendChild(l)}else l.href='/filora-theme.css?v=9'}
function ensurePromoterAccountTheme(){if(!/promoter-(settings|submissions|wallet)\.html$/i.test(location.pathname))return;var old=document.getElementById('promoter-account-theme-css');if(old)old.remove();var l=document.createElement('link');l.id='promoter-account-theme-css';l.rel='stylesheet';l.href='/promoter-account-theme.css?v=11';document.head.appendChild(l)}
function setupPromoterMobileNav(){if(!/promoter-dashboard\.html$/i.test(location.pathname))return;var bottom=document.querySelector('.bottom');if(!bottom){bottom=document.createElement('nav');bottom.className='bottom';document.body.appendChild(bottom)}bottom.innerHTML='<button class="active" data-page="home"><i>⌂</i>Home</button><button data-page="tasks"><i>✓</i>Tasks</button><button data-page="create" aria-label="Create Task"><i>＋</i></button><button data-page="wallet"><i>₦</i>Wallet</button><button data-page="profile"><i>☰</i>More</button>'}
function setupPromoterSharedNav(){if(!isPromoterPage())return;if(document.getElementById('tvx-promoter-nav-loader'))return;var s=document.createElement('script');s.id='tvx-promoter-nav-loader';s.src='/promoter-nav.js?v=2';document.head.appendChild(s)}
function setupWorkerMobileNav(){if(isPromoterPage())return;var b=document.querySelector('nav.bottom');if(!b)return;var p=(location.pathname||'').split('/').pop().toLowerCase(),h=p==='dashboard.html'||p==='';var w=p==='wallet.html'||p==='withdraw.html'||p==='payout-settings.html';var r=p==='referrals.html';var m=['more.html','profile.html','plan.html','security.html','activation.html','support.html','terms.html','privacy.html'].includes(p);b.innerHTML='<a class="'+(h?'active':'')+'" href="dashboard.html"><b>⌂</b>Home</a><a class="'+(w?'active':'')+'" href="wallet.html"><b>◉</b>Wallet</a><a class="plus" href="tasks.html" aria-label="Tasks"><b>✓</b></a><a class="'+(r?'active':'')+'" href="referrals.html"><b>👥</b>Referral</a><a class="'+(m?'active':'')+'" href="more.html"><b>☰</b>More</a>'}
function setupRoleProtection(){if(isPromoterPage())return;var path=(location.pathname||'').split('/').pop().toLowerCase();var wo=['plan.html','security.html','activation.html','worker-activation.html','activation-callback.html','worker-tasks.html'];if(wo.indexOf(path)<0)return;var tries=0;function check(){tries++;try{var c=getClient();if(!c){if(tries<160)setTimeout(check,50);return}c.auth.getUser().then(function(r){if(r.error||!r.data||!r.data.user){location.replace('login.html');return null}return c.from('profiles').select('role').eq('id',r.data.user.id).maybeSingle()}).then(function(x){if(!x)return;var role=String(x.data&&x.data.role||'').toLowerCase();if(wo.indexOf(path)>=0&&role!=='worker')location.replace('promoter-dashboard.html')}).catch(function(){location.replace('dashboard.html')})}catch(e){if(tries<160)setTimeout(check,50)}}check()}
function setupLoginSession(){var p=(location.pathname||'/').toLowerCase();if(isPromoterPage())return;var pub=p==='/'||p===''||/\/(index|login|register|forgot-password|reset-password|promoter-register|promoter-login)\.html$/i.test(p);if(!pub&&sessionStorage.getItem(SESSION_KEY)!=='1'){location.replace('login.html');return}var tries=0;function bind(){tries++;try{var c=getClient();if(c&&c.auth&&typeof c.auth.onAuthStateChange==='function'){c.auth.onAuthStateChange(function(e){if(e==='SIGNED_IN')sessionStorage.setItem(SESSION_KEY,'1');if(e==='SIGNED_OUT')sessionStorage.removeItem(SESSION_KEY)});return}}catch(e){}if(tries<160)setTimeout(bind,50)}bind()}
function setup(){apply();ensureFilora();ensurePromoterAccountTheme();setupPromoterMobileNav();setupPromoterSharedNav();setupWorkerMobileNav();setupRoleProtection()}
try{localStorage.setItem(KEY,'dark')}catch(e){}setupLoginSession();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();